# Generated by Django 6.0.3 on 2026-03-09 01:17

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models.logo_upload_path, verbose_name='شعار المكتب')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='العملة')),
                ('commercial_registration', models.CharField(blank=True, max_length=100, verbose_name='السجل التجاري')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الترخيص')),
            ],
            options={
                'verbose_name': 'ملف المكتب',
                'verbose_name_plural': 'ملف المكتب',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('lawyer', 'محامي'), ('secretary', 'سكرتير'), ('accountant', 'محاسب')], default='lawyer', max_length=20, verbose_name='الدور')),
                ('bar_number', models.CharField(blank=True, max_length=50, verbose_name='رقم القيد')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='التخصص')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=core.models.profile_picture_upload_path, verbose_name='صورة الملف الشخصي')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم العميل')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة')], default='individual', max_length=20, verbose_name='نوع العميل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=20, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'indexes': [models.Index(fields=['client_id'], name='core_client_client__6790f9_idx'), models.Index(fields=['status'], name='core_client_status_d6704e_idx'), models.Index(fields=['type'], name='core_client_type_a6341f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القضية')),
                ('subject', models.CharField(max_length=500, verbose_name='موضوع القضية')),
                ('court', models.CharField(blank=True, max_length=200, verbose_name='المحكمة')),
                ('case_type', models.CharField(blank=True, max_length=100, verbose_name='نوع القضية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('active', 'قيد النظر'), ('pending', 'معلق'), ('won', 'منجز'), ('lost', 'خاسر'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('urgent', 'عاجل'), ('high', 'عالي'), ('normal', 'عادي'), ('low', 'منخفض')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('position', models.CharField(choices=[('plaintiff', 'مدعي'), ('defendant', 'مدعى عليه')], default='plaintiff', max_length=20, verbose_name='موقف المكتب')),
                ('next_session_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الجلسة القادمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'قضية',
                'verbose_name_plural': 'القضايا',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('meeting', 'اجتماع'), ('call', 'مكالمة'), ('consultation', 'استشارة'), ('court_visit', 'زيارة محكمة'), ('signing', 'توقيع')], default='meeting', max_length=30, verbose_name='النوع')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='المكان')),
                ('datetime', models.DateTimeField(verbose_name='التاريخ والوقت')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('completed', 'منتهي'), ('cancelled', 'ملغي')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات/توثيق الكلام')),
                ('amount_collected', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المبلغ المحصل')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('completed', 'منتهي')], default='new', max_length=20, verbose_name='الحالة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'استشارة',
                'verbose_name_plural': 'الاستشارات',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('type', models.CharField(max_length=100, verbose_name='نوع العقد')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='القيمة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_signature', 'بانتظار التوقيع'), ('active', 'نشط'), ('expired', 'منتهي')], default='draft', max_length=30, verbose_name='الحالة')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.contract_upload_path, verbose_name='الملف')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإقرار')),
                ('type', models.CharField(max_length=200, verbose_name='نوع الإقرار')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('final', 'نهائي'), ('signed', 'موقع')], default='draft', max_length=20, verbose_name='الحالة')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.declaration_upload_path, verbose_name='الملف')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'إقرار',
                'verbose_name_plural': 'الإقرارات',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.document_upload_path, verbose_name='الملف')),
                ('doc_type', models.CharField(choices=[('contract', 'عقد'), ('court_doc', 'مستند محكمة'), ('evidence', 'دليل'), ('correspondence', 'مراسلات'), ('id', 'هوية/وثيقة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المستند')),
                ('security_level', models.CharField(choices=[('normal', 'عادي'), ('confidential', 'سري')], default='normal', max_length=20, verbose_name='مستوى السرية')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.case', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('category', models.CharField(choices=[('court_fees', 'رسوم محكمة'), ('transport', 'نقل'), ('documents', 'مستندات'), ('utilities', 'مرافق'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='الفئة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('receipt', models.FileField(blank=True, null=True, upload_to=core.models.expense_receipt_upload_path, verbose_name='إيصال')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.case', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('hourly', 'بالساعة')], default='fixed', max_length=20, verbose_name='نوع الأتعاب')),
                ('agreed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المبلغ المتفق عليه')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('partial', 'مدفوع جزئياً')], default='pending', max_length=20, verbose_name='الحالة')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.case', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'أتعاب',
                'verbose_name_plural': 'الأتعاب',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='رقم الفاتورة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المجموع الفرعي')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='مبلغ الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('paid', 'مدفوع'), ('pending', 'معلق'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='LookupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('courts', 'المحاكم'), ('case_types', 'أنواع القضايا'), ('expense_categories', 'فئات المصروفات')], max_length=30, verbose_name='الفئة')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'بيانات مرجعية',
                'verbose_name_plural': 'البيانات المرجعية',
                'indexes': [models.Index(fields=['category'], name='core_lookup_categor_f89446_idx'), models.Index(fields=['is_active'], name='core_lookup_is_acti_fd08f4_idx')],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('session', 'جلسة'), ('payment', 'دفعة'), ('task', 'مهمة'), ('case', 'قضية'), ('contract', 'عقد')], default='case', max_length=20, verbose_name='نوع الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستهدف')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة'), ('government', 'جهة حكومية'), ('entity', 'جهة أخرى')], default='individual', max_length=20, verbose_name='نوع الخصم')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('opponent_lawyer', models.CharField(blank=True, max_length=200, verbose_name='محامي الخصم')),
            ],
            options={
                'verbose_name': 'خصم',
                'verbose_name_plural': 'الخصوم',
                'indexes': [models.Index(fields=['type'], name='core_oppone_type_b09ce6_idx')],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='opponents',
            field=models.ManyToManyField(blank=True, related_name='cases', to='core.opponent', verbose_name='الخصوم'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل'), ('check', 'شيك')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.fee', verbose_name='الأتعاب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
        migrations.CreateModel(
            name='PowerOfAttorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('general', 'عام'), ('special', 'خاص'), ('judicial', 'قضائي'), ('real_estate', 'عقاري')], default='special', max_length=30, verbose_name='نوع الوكالة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='الجهة المصدرة')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.poa_upload_path, verbose_name='الملف')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expiring_soon', 'قارب على الانتهاء'), ('expired', 'منتهي')], default='active', max_length=20, verbose_name='الحالة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers_of_attorney', to='core.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'وكالة',
                'verbose_name_plural': 'التوكيلات',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('session_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الجلسة')),
                ('minutes', models.TextField(blank=True, verbose_name='محضر الجلسة')),
                ('attachments', models.FileField(blank=True, null=True, upload_to=core.models.session_attachment_upload_path, verbose_name='مرفقات')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'منتهية'), ('postponed', 'مؤجلة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.case', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد التنفيذ'), ('review', 'مراجعة'), ('done', 'منتهي')], default='new', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('urgent', 'عاجل'), ('high', 'عالي'), ('normal', 'عادي'), ('low', 'منخفض')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='المكلف')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.case', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_73872d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='core_user_is_acti_8c954f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client'], name='core_appoin_client__65f08a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['datetime'], name='core_appoin_datetim_310bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='core_appoin_status_e978b8_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['client'], name='core_consul_client__15af53_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['date'], name='core_consul_date_cc7572_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='core_consul_status_1450b7_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='core_contra_contrac_fac21c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client'], name='core_contra_client__93eb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='core_contra_status_2b38a6_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='core_contra_end_dat_8f1582_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['declaration_number'], name='core_declar_declara_003702_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['client'], name='core_declar_client__cc5b52_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['date'], name='core_declar_date_1bcc28_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case'], name='core_docume_case_id_59bcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type'], name='core_docume_doc_typ_a55021_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='core_docume_uploade_e13ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['case'], name='core_expens_case_id_54045a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='core_expens_categor_358de0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='core_expens_date_d957f6_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['case'], name='core_fee_case_id_5272e2_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['status'], name='core_fee_status_1877d3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='core_invoic_client__f81038_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date'], name='core_invoic_date_85ec84_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_user'], name='core_notifi_target__4b2c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='core_notifi_is_read_127eae_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='core_case_case_nu_de3c58_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='core_case_status_59308c_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['next_session_date'], name='core_case_next_se_809340_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='core_case_created_3c706e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['fee'], name='core_paymen_fee_id_f094b5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='core_paymen_date_122a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='powerofattorney',
            index=models.Index(fields=['client'], name='core_powero_client__e8356c_idx'),
        ),
        migrations.AddIndex(
            model_name='powerofattorney',
            index=models.Index(fields=['expiry_date'], name='core_powero_expiry__2f7d99_idx'),
        ),
        migrations.AddIndex(
            model_name='powerofattorney',
            index=models.Index(fields=['status'], name='core_powero_status_d832b7_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['case'], name='core_sessio_case_id_01854a_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date'], name='core_sessio_date_0dafbc_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='core_sessio_status_45f1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='core_task_assigne_5f3995_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='core_task_status_e18e62_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='core_task_due_dat_d0a0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['case'], name='core_task_case_id_63a5c8_idx'),
        ),
    ]
