# Generated by Django 6.0.3 on 2026-03-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.case', verbose_name='القضية'),
        ),
    ]
