# Generated by Django 6.0.3 on 2026-03-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المكتب'),
        ),
    ]
