# Generated by Django 6.0.3 on 2026-03-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_officeprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة القضية'),
        ),
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
    ]
