# Generated by Django 6.0.3 on 2026-03-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_case_case_year_case_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='position',
            field=models.CharField(blank=True, choices=[('plaintiff', 'مدعي'), ('defendant', 'مدعى عليه')], max_length=20, verbose_name='موقف المكتب'),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('high', 'عاجل'), ('normal', 'عادي'), ('low', 'منخفض')], default='normal', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('active', 'نشطة'), ('pending', 'معلقة'), ('won', 'مكسوبة'), ('closed', 'مغلقة')], default='active', max_length=20, verbose_name='حالة القضية'),
        ),
    ]
