# Generated by Django 6.0.3 on 2026-03-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_case_position_alter_case_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, verbose_name='الرقم القومي'),
        ),
    ]
