# Generated by Django 6.0.3 on 2026-03-16 06:25

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.client_attachment_path, verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'مرفق عميل',
                'verbose_name_plural': 'مرفقات العميل',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='additional_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم إضافي'),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان بالتفصيل'),
        ),
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.CharField(blank=True, max_length=100, verbose_name='الوظيفة'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['national_id'], name='core_client_nationa_aa0cc0_idx'),
        ),
        migrations.AddField(
            model_name='clientattachment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.client', verbose_name='العميل'),
        ),
    ]
